### ISSUE TITLE
Getting failures running chrome beta and unstable

### ISSUE THREAD

**Issue by aullman** [DamonOehlman/travis-multirunner#27]
https://travis-ci.org/DamonOehlman/travis-multirunner/jobs/248615131#L688

```
+./browsers/bin/chrome-beta --version
./browsers/bin/chrome-beta: symbol lookup error: ./browsers/bin/chrome-beta: undefined symbol: gdk_screen_get_monitor_scale_factor
```

**Comment by fippo** [comment]
w00t? looking at adapter that uses dist: trusty

**Comment by aullman** [comment]
@fippo are you saying dist:trusty works?

I found someone else that had the same issue, https://github.com/GoogleChrome/lighthouse/issues/2544

Their [fix](https://github.com/GoogleChrome/lighthouse/pull/2547) was to just use chrome stable instead of Canary from what I can tell :)

**Comment by aullman** [comment]
Good call @fippo! https://travis-ci.org/aullman/travis-multirunner/jobs/249511438
