### ISSUE TITLE
Make multirunner more useful for executing locally?

### ISSUE THREAD

**Issue by alvestrand** [DamonOehlman/travis-multirunner#3]
This is as much a query as a bug, to see if it's worthwhile making a pull request...
travis-multirunner executed locally has two irritating properties:
- it puts links into ~/bin
- it leaves downloaded tar.gz files in the home directory of the project.

I think it would be nicer if we had a subdir of the project directory called "travis-multirunner-workdir" where we could keep both the symlinks and the packages, and advise users that they could add this to their .gitignore file to avoid having it show up every time as "untracked file".

What do you think?

**Comment by DamonOehlman** [comment]
@alvestrand The second point definitely makes sense to me, so I'd definitely welcome a PR for that :)

The links in ~/bin are a little strange also I guess in retrospect, so that should probably go as well.  Maybe as a separate PR though?
