### ISSUE TITLE
issues with permission on setup.sh?

### ISSUE THREAD

**Issue by fippo** [DamonOehlman/travis-multirunner#32]
in the last two weeks i've run into issues with the permission bit on setup.sh:
```
Warning: Command failed: BROWSER=${BROWSER-chrome} BVER=${BVER-stable} ./node_modules/travis-multirunner/setup.sh
/bin/sh: 1: ./node_modules/travis-multirunner/setup.sh: Permission denied
 Use --force to continue.
```
might be related to npm updates. Does not seem to happen on travis afaics.

The file permissions look good to me...

**Comment by DamonOehlman** [comment]
@fippo interesting - so this is attempting to run within another CI system?  Or something else?

**Comment by fippo** [comment]
this was locally on a ubuntu machine. Coming from here:
https://github.com/webrtc/adapter/blob/master/Gruntfile.js#L73

(also cc @kaptenjansson)

**Comment by fippo** [comment]
https://github.com/npm/npm/issues/18324 -- now fixed.
