### ISSUE TITLE
browsers.contralis.info is gone?

### ISSUE THREAD

**Issue by fippo** [DamonOehlman/travis-multirunner#34]
looks like browsers.contralis.info is gone and the main domain is showing a namecheap site.

I never figured out who was running this useful service. @DamonOehlman @nathanoehlman?

**Comment by DamonOehlman** [comment]
@fippo That was @nathanoehlman - Nathan something you can fix?  Or possible to host the site elsewhere?

**Comment by silviapfeiffer** [comment]
Looks like it's back :-)

**Comment by fippo** [comment]
woho, green dashboard. Thanks for fixing it!

**Comment by silviapfeiffer** [comment]
I did nothing - thanks to @nathanoehlman :-)

**Comment by nathanoehlman** [comment]
Sorry about the interruption in service - I missed the renewal for the contralis.info domain, and once I missed it, the namecheap domain servers took an excruciating amount of time to update back from the parking page.

**Comment by fippo** [comment]
ping... now it gives an "application error"?

**Comment by lgrahl** [comment]
I don't want to be disrespectful (not even close, this microservice is cool!) but can whoever operates that server open the code, so we don't have a single point of failure in the future?

**Comment by fippo** [comment]
also wondering why we don't use https://github.com/nathanoehlman/browser-sleuth directly, thanks @lgrahl :-)

**Comment by fippo** [comment]
ironically browser-sleuth is broken because https://omahaproxy.appspot.com/all/json errors... :-)

**Comment by DamonOehlman** [comment]
> I don't want to be disrespectful (not even close, this microservice is cool!) but can whoever operates that server open the code, so we don't have a single point of failure in the future?

@nathanoehlman Any ideas on this?  Perhaps it would be possible to tweak your code (which AFAIK runs on a VPS somewhere) to be heroku deploy friendly?  I still believe they offer free hosting for light traffic sites and I imagine `browsers.contralis.info` is probably pretty low traffic.

**Comment by nathanoehlman** [comment]
Hi all,

Sorry about this - I have a terrible tendency to forget to renew my obscure domains, so it's definitely worth moving away from a reliance on that :)

The server itself is actually already hosted on Heroku, and running on the free tier hosting, so it should exist for as long as Heroku honours that (and has the added upshot of not relying on me remembering to pay), so it may be worth just changing the address to that - https://browser-version-api.herokuapp.com/

Alternatively, the code for the service is available at https://github.com/nathanoehlman/browser-version-api if anyone wants to spin up their own alternate instance.

**Comment by fippo** [comment]
works for me :-)

**Comment by fippo** [comment]
https://browser-version-api.herokuapp.com/linux/firefox/unstable 404s? Chrome works...

**Comment by fippo** [comment]
ah, lets use #56
