### ISSUE TITLE
firefox esr is still 52?

### ISSUE THREAD

**Issue by fippo** [DamonOehlman/travis-multirunner#46]
that is what https://browser-version-api.herokuapp.com/linux/firefox/esr says

https://download.mozilla.org/?product=firefox-esr-latest&os=linux&lang=en-US gives me 60.2.0 which (thankfully) no longer requires ancient pre-marionette geckodriver

**Comment by DamonOehlman** [comment]
@nathanoehlman made the source for that available @

https://github.com/nathanoehlman/browser-version-api

Can probably get some details as to what is going on there...

**Comment by fippo** [comment]
that gives me the correct version (60) -- and now https://browser-version-api.herokuapp.com/linux/firefox/esr does too.  Once you ask for it, it starts working? :-)
