### ISSUE TITLE
chromedriver only works with latest versions

### ISSUE THREAD

**Issue by fippo** [DamonOehlman/travis-multirunner#48]
see https://github.com/giggio/node-chromedriver/issues/237
https://github.com/giggio/node-chromedriver#versioning actually describes the right thing to do but it means a different process since one can no longer just depend on having chromedriver as a dependency in package.json but most now pull it (which we currently don't but maybe we should?) with an explicit version

**Comment by fippo** [comment]
#49 should allow getting that fixed

**Comment by giggio** [comment]
Please see comments on https://github.com/giggio/node-chromedriver/issues/237 as we have added more options regarding versions.

**Comment by fippo** [comment]
--disable-build-check solves this
