### ISSUE TITLE
Failing to retreive browser version for firefox - browser-version-api 404

### ISSUE THREAD

**Issue by maikthomas** [DamonOehlman/travis-multirunner#56]
Hi there! I noticed that firefox is not installing due to a 404 not found response from 
https://browser-version-api.herokuapp.com/linux/firefox/stable

Is that a heroku app of this project?
https://github.com/nathanoehlman/browser-version-api

Anything we can do to fix this?

**Comment by fippo** [comment]
looks like download.mozilla.org no longer works. Tagging @jan-ivar

**Comment by fippo** [comment]
so it fails in applyRegex with:
```
/^.*((?:Firefox |firefox-)[0-9\.ba]+\..*[exe|dmg|tar.bz2]).*/
```
and a download url of
`https://download-installer.cdn.mozilla.net/pub/firefox/releases/107.0/win32/en-US/Firefox Setup 107.0.exe`

**Comment by fippo** [comment]
so it seems like the file name convention changed which requires this regexp
```
/^.*((?:Firefox |firefox-)(.*)[0-9\.ba]+\..*[exe|dmg|tar.bz2]).*/
```
(i.e. something between "Firefox" and the version)?

**Comment by maikthomas** [comment]
Looks like the herokuapp went offline... https://browser-version-api.herokuapp.com/linux/chrome/stable

**Comment by DamonOehlman** [comment]
Feels like it might be worth making the endpoint that is queried for versions configurable (via an ENV var) in the setup script:

https://github.com/DamonOehlman/travis-multirunner/blob/45c8b7d327d5f1f665650988f244c7001bafd5fb/setup.sh#L52

Gives people some ability to host their own equivalent service if that's what they are keen on doing, and gets us away from any single point of failure.  I guess additionally we should look at moving the default away from heroku if it's proving to be mostly unreliable.  I might have a poke around and see what might be a good alternative for hosting something.  To be honest, I'm not doing a lot in JS land at the moment but that doesn't mean that I wouldn't be happy to whip something up in either Kotlin or rust as an alternative hosted service :)

**Comment by fippo** [comment]
just calling browser-sleuth directly from travis-multirunner should be easy enough (and a tiny bit faster even?)
